set nocompatible
set encoding=utf-8

filetype plugin indent on

" Basic settings
set backspace=indent,eol,start
set visualbell
set noerrorbells

" Leader key
let mapleader = ","

" Quick escape and save mappings
inoremap <C-j> <Esc>
inoremap <F2> <C-o>:w<CR>
nnoremap <F2> :w<CR>
nnoremap <C-d> :q<CR>

" Line numbers
set invnumber
nmap <Leader>N :set invnumber<CR>
set pastetoggle=<F3>

" Clipboard
set clipboard=unnamed

" Invisible characters
set listchars=tab:❘-,trail:·,extends:»,precedes:«,nbsp:×
set nolist
noremap <Leader>? :set list!<CR>

" Tabs and indentation
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab
set autoindent
set smartindent
set cindent
set copyindent

" Buffer and display settings
set hidden
set cursorline
set nowrap
set ruler
set showcmd
set showmatch
set foldlevelstart=20
set history=1000
set undolevels=1000

" Search settings
set incsearch
set hlsearch
set ignorecase
set smartcase

" Wildmenu
set wildmode=list:longest
set wildignore=*.swp,*.bak,*.pyc,*.class,target,build,node_modules,logs,out

" Backup and swap
set nobackup
set noswapfile

" Mouse support
if has('mouse')
    set mouse=a
    if !has('nvim')
        set ttymouse=xterm2
    endif
endif

" Syntax highlighting
if &t_Co > 2 || has("gui_running")
    set t_Co=256
    syntax on
    set omnifunc=syntaxcomplete#Complete
endif

" GUI settings
if has("gui_running")
    set guioptions=egt
    set guioptions-=mrT
endif

" Autocmds
if has("autocmd")
    augroup vimrcEx
    au!

    " Jump to last cursor position
    autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

    " Remove trailing whitespace on save
    autocmd BufWritePre * :%s/\s\+$//e

    augroup END

    set completeopt=menuone,menu,longest
endif

" Netrw settings
let g:netrw_gx="<cWORD>"

" Timeout settings
set ttimeoutlen=50

" Sudo write
cmap w!! %!sudo tee > /dev/null %

" Clear search highlighting
nnoremap <Leader><space> :nohlsearch<CR>

" Navigate splits with Ctrl+hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Buffer navigation
nnoremap <Leader>n :bnext<CR>
nnoremap <Leader>p :bprev<CR>
nnoremap <Leader>d :bdelete<CR>

" Colorscheme - simple terminal-friendly scheme
set background=dark
colorscheme pablo

" Local overrides
if filereadable(expand("~/.vimrc_local"))
  source ~/.vimrc_local
endif
