# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

install coreutils --default-names
install moreutils
install gnu-sed --default-names

install tree

install zsh
install git
install python
install ruby
install --HEAD macvim

install lynx
install pv
install zopfli

# config
install autoenv

# tmux
install tmux
install reattach-to-user-namespace

install imagemagick --with-webp

# Remove outdated versions from the cellar
cleanup
